name: Run benchmark

on:
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install build-essential libssl-dev git -y
          git clone https://github.com/wg/wrk.git wrk
          cd wrk
          make
          # move the executable to somewhere in your PATH, ex:
          sudo cp wrk /usr/local/bin
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: 1.6.1
      - run: |
          mkdir -p artifacts          
          cat > artifacts/message.md <<EOF
          # Benchmark results

          <details>
          <summary>PR to merge $GITHUB_HEAD_REF $GITHUB_SHA -> $GITHUB_BASE_REF</summary>

          \`\`\`$(make benchmark)
          \`\`\`

          </details>
          EOF
      - uses: actions/upload-artifact@v1
        with:
          name: pr_message
          path: artifacts
